### ISSUE TITLE
Add test for very complex shape (>65535 indices when tesselated)

### ISSUE THREAD

**Issue by Herschel** [ruffle-rs/visual-tests#1]
Example:
https://github.com/ruffle-rs/ruffle/issues/2241
Usually made using the "Trace Bitmap" functionality in Flash.

**Comment by Herschel** [comment]
Love the choice of picture, but if possible, let's try to use an image in the public domain or with a permissive license. Sorry if this seems overly paranoid, thanks!

**Comment by spikything** [comment]
@Herschel this issue should be marked as closed.

**Comment by Herschel** [comment]
Closed by #1 (thanks @spikything!)
